### PR TITLE
Add playlist/genre to the search by query intent. Fix a crash on failed search; interpret empty query search as play all songs

### PR DESCRIPTION
**Pull request by gaycodegal**
This allows AIs to open playlist by name.
- https://developer.android.com/guide/components/intents-common#PlaySearch

I've been testing using the intents from https://github.com/hobbycommandline/Hobby-Voice-Command-Line but I've been consulting the official google docs and the code I wrote complies with google's standards.

### CODE REVIEW

**Comment by gaycodegal** [comment]
I realized the app doesn't support genre query intents either yet so I'll have to add that one in too. Either in this PR or another depending on when it gets reviewed and when i write the genre code.

**Comment by gaycodegal** [comment]
I have realized on further use of this feature myself that first match is not really what a user wants, they want the most exact match, which is to say the shortest playlist or genre name that contains their search query (as opposed to the first genre of playlist that contains their query). Updating the code accordingly now.

**Comment by gaycodegal** [comment]
Added "closest match" and genre search. Now good to submit.

Total change summary:
- Add playlist search based on "closest match"
- Add genre search based on "closest match"
- Fix a crash on failed search
- "empty" search -> play all songs

Closest match:
* Shortest string > string with compareTo closer to front
* or if neither of those two cases satisfied use first found
* match

**Comment by gaycodegal** [comment]
edit: don't submit yet, need to verify a flow

**Comment by gaycodegal** [comment]
all good to go, the confusion from earlier today was not due to code errors here, tested all flows and confirmed it worked.

**Comment by soncaokim** [comment]
Thanks

**Pull request merged**
