### PR TITLE
Highlight playing song

### PR DESCRIPTION
**Pull request by soncaokim**
First attempt to address https://github.com/AdrienPoupa/VinylMusicPlayer/issues/127 by using font decoration.

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
This looks great! Can you just merge the latest changes from the master to your branch so both branches are in sync ?

**Comment by soncaokim** [comment]
Please hold back this PR, at least in the search view multiple songs are marked as playing. 

Havent managed to reproduce consistently though.

**Comment by soncaokim** [comment]
Some uodate on this:

The "is playing" indicator seems ok (bold font+icon), but when the next song is played the decoration on previous one doesnt gets updated properly (font stays bold).

For ex: play a song, then jump to the album/artist and wait till the end of the song.

Probably linked: search for a common pattern that matches the currently playing song. The search result contains the currently played song decorated, but some other similar song as well.

My current guess is that the changes on the underlying dataset isnt propagated to the decoration code now.

So help is appreciated :-)

**Comment by GeoZac** [comment]
@soncaokim The indicator icon is white on white on light theme.
The indicator replacing the albumart in the lists seems inconsistent.

**Comment by soncaokim** [comment]
> @soncaokim The indicator icon is white on white on light theme.
Noted

> The indicator replacing the albumart in the lists seems inconsistent.
what do you mean by inconsistent?

**Comment by GeoZac** [comment]
> what do you mean by inconsistent?

Just my personal opinion, removing the album art for currently playing item looks bad.

**Comment by soncaokim** [comment]
> Just my personal opinion, removing the album art for currently playing item looks bad.

Noted. 

Once I've cleaned up the duplications and other experimental codes, I can revisit the decoration bits. Maybe overlaying the speaker icon over the album art, or an animated icon (like Google Music).

I've chosen to use the speaker icon to be consistent with the current choice (used in the current playing card).

**Comment by soncaokim** [comment]
@adrien I'm somewhat happy with the state of this PR. There is one refactoring chance on the album art loading - not sure I want to do it right now :-)

@geozac: Just had a quick look on the icon/indicator on white theme. While I'm seeing the issue, I'm not sure what would be the precise fix for that (given that the same icon is displayed correctly elsewhere). If you have an idea/a patch, it's more than appreciated.

**Comment by AdrienPoupa** [comment]
Hi @soncaokim, thanks for your work!

I applied your changes and the song does not appear in bold unless I scroll so that I don't see it anymore - and from there if I go back to it, then it appears.

You can see it the attached video gif.
ScreenRecord-2019-04-24-22-13-19

**Comment by soncaokim** [comment]
> I applied your changes and the song does not appear in bold unless I scroll so that I don't see it anymore - and from there if I go back to it, then it appears.

I guess this implies that I need to catch the onPlayStateChanged as well (right now only the onPlayingMetaChanged event is propagated).

I'll have a look at this (probably next week when I get a more stable connection).

Son

**Comment by soncaokim** [comment]
@adrien, please have a second look. It's mainly this commit https://github.com/AdrienPoupa/VinylMusicPlayer/pull/136/commits/c565f550ba345415633afa34dd86e37e9b5a05da that tackles what you observed.

Thanks

Son

**Comment by AdrienPoupa** [comment]
@soncaokim hey, sorry I was busy. I tried it, it looks good. One thing though: I noticed that you added the icon on the search page. Until now, the albums images were not loaded there. Now there is an empty space or the playing indication. To remain consistent, can you either:
* Add the album cover on the newly created space
* Remove the icon on the search page and only keep the bold text

Thanks!

**Comment by soncaokim** [comment]
Hi,

For the search list, I did it intentionally 😁

If only bold is shown (no icon), it wont be consistent with the way the playing song is shown in other views.
If the album image is shown, it can be mistaken as an album.

If the blank space troubles you, we can use a generic track icon.

S.

**Pull request merged**
