### PR TITLE
Add favorite button to notifications

### PR DESCRIPTION
**Pull request by jamerst**
Address #151 

I'm personally unsure whether to keep the button in the small notification, it may make things a little cramped.

### CODE REVIEW

**Comment by soncaokim** [comment]
Can you please attach a screenshot showing off the new addition?

**Comment by jamerst** [comment]
These are the two notifications after the addition.

image
image

**Comment by soncaokim** [comment]
Thanks, based on the screenshots I assume that we are talking about widgets here, not the notification.

Looks fine by the way. 

You may need to update the sample images, those used by Android as sample when creating new widgets. If I m not wrong they are under app/src/main/res/drawable

**Comment by jamerst** [comment]
Those are the notifications, the "Classic notification design" option is just enabled.

I can't attach a screenshot right now, but the normal notification isn't a problem since the small notification can only have a maximum of 3 actions.

**Comment by soncaokim** [comment]
I stand corrected.

**Comment by jamerst** [comment]
For reference, the normal notification looks like this
image

**Pull request merged**
