### PR TITLE
Fast forwad was not put on flat palyer

### PR DESCRIPTION
**Pull request by Octoton**
Thus, I have just taken the code from the other fragment and past it

See issue84 and https://github.com/AdrienPoupa/VinylMusicPlayer/pull/404

### CODE REVIEW

**Comment by soncaokim** [comment]
Thanks for spotting this.

Can you please find a way to avoid copy/paste, probably by converting the inner class PrevNextButtonOnTouchListener to a dedicated parameterized class (parameterized = specifiy the direction of the action, either backward or forward)

**Comment by Octoton** [comment]
Well this is only two touchlistner

**Comment by Octoton** [comment]
@soncaokim is it better that way ?

**Comment by soncaokim** [comment]
It is better, thanks.

**Review by soncaokim — APPROVED** [review]

**Pull request merged**
