### PR TITLE
Add play queue progress to up next

### PR DESCRIPTION
**Pull request by jamerst**
Add current play queue position and length alongside playtime remaining

image

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
Hi,

Actually it doesn't seem to play nice with the shuffle play feature, can you check?

**Comment by jamerst** [comment]
Hi,

Can you clarify the issue? What do you mean by shuffle play, and what seems to be the problem with it?

**Comment by AdrienPoupa** [comment]
Enable shuffle play (crossing arrows icons next to the next song icon), the queue counter will be increased by 1 even though the actual position of the song is different

**Comment by jamerst** [comment]
The intention of the feature is to show the progress through the current play queue. When shuffle is enabled, the play queue itself is shuffled, the current song is set as the first, and all other songs previously in the play queue shuffled randomly to make the rest of the queue.

When the next song is played, the shuffled queue is simply advanced by 1, so the counter just increments by 1. If the counter was instead set to show the original position of the song in the unshuffled queue, it wouldn't show progress through the current, now shuffled, play queue.

**Pull request merged**
