### PR TITLE
French translation followup

### PR DESCRIPTION
**Pull request by GladiusTM**

### CODE REVIEW

**Comment by GladiusTM** [comment]
Hello, I have finished to reorganize and check the french translation strings file, I have pushed it and made the pull request, but it seems that there is an error and I don't understand the problem.
Can you take look if you have the time? Thank you

**Comment by soncaokim** [comment]
There is at least some merge conflict - i.e. you and someone has made changes on the same file and/or same set of lines.
This confuses Git (the source code management app) and it refuses to merge.

You'll need to look at the conflict and resolve them manually. Once done you can resubmit the PR.

**Comment by GladiusTM** [comment]
> There is at least some merge conflict - i.e. you and someone has made changes on the same file and/or same set of lines. This confuses Git (the source code management app) and it refuses to merge.
> 
> You'll need to look at the conflict and resolve them manually. Once done you can resubmit the PR.

I have managed to fix the problem.

**Comment by soncaokim** [comment]
Thanks, next time please refrain from moving around the lines since it is impossible to check the changes.

**Pull request merged**
