### PR TITLE
Fix the ellipsize bug

### PR DESCRIPTION
**Pull request by soncaokim**
This fixes the https://github.com/AdrienPoupa/VinylMusicPlayer/issues/169.
@theduffmaster Can you please have a look as well?

### CODE REVIEW

**Comment by theduffmaster** [comment]
Nice fix, this must have slipped by when I was reviewing but my mistake is obvious now. Thank you soncaokim

**Comment by AdrienPoupa** [comment]
Did you test this for Android <= 6?

**Comment by soncaokim** [comment]
Was there a related behaviour/API change on Android 6? Otherwise we need to test the on all versions to be sure.

**Comment by AdrienPoupa** [comment]
If you check the Java doc of the functions you modified you will see it consists of hacks I had to do to make the scrolling title feature work on Android 6 and below. Otherwise it would display an empty text.

**Comment by soncaokim** [comment]
Thanks,  I will revert once this is done.

**Comment by soncaokim** [comment]
Alright, I'm putting back the WIP tag on this pull request.

On Android 6: it crashed -> the fix was easy (restoring the findByTag function) -> no text / truncated text.
As if the layout size is misreported.

Any insight will be very helpful :-)

**Comment by soncaokim** [comment]
Weird thing is the text is truncated on Android 6 even with the original code.

**Comment by soncaokim** [comment]
Getting back to this...

> If you check the Java doc of the functions you modified you will see it consists of hacks I had to do to make the scrolling title feature work on Android 6 and below. Otherwise it would display an empty text.

My memory fails me: I cannot recall what was the issue with Android 6. Running the code of this branch on a Nexus 4 (API 23) provides seemingly correct behaviour - i.e. scrolling text, correct truncation, no empty text...

The only thing I've done was rebasing on master (i.e. having the latest changes on the dependencies etc).

@AdrienPoupa Can you please have a look and give me a second opinion on this?

Thanks

**Comment by AdrienPoupa** [comment]
Those were the issues on Android 6:
https://github.com/AdrienPoupa/VinylMusicPlayer/issues/110
https://github.com/AdrienPoupa/VinylMusicPlayer/issues/107

You may also want to run it for 4.4.4 for good measure.

If it is working now, then all good!

**Comment by soncaokim** [comment]
Checked on emulator with API level 19, I think we are good to go (unless I've overlooked something)

**Comment by soncaokim** [comment]
@adrienpoupa can you please merge this PR?

**Pull request merged**
