### PR TITLE
Add ReplayGain support and preamp

### LINKED ISSUE #31: [Feature Request] ReplayGain support
Hello!

Would you please implement support for replaygain?

This is the only feature I am missing from VinylMusicPlayer.

Thanks!

### PR DESCRIPTION
**Pull request by knacky34**
This fixes #31, I think it will be a great addition to this app :)

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
Hi knacky, first of all, thanks for contributing! :-)

I have looked at your PR thoroughly, and there's one thing I don't really understand: why would we need a full blown tagging library whereas we already use [jaudiotagger](https://github.com/AdrienPoupa/jaudiotagger)?

From what I see, the BASTP library is coming from the [Vanilla player](https://github.com/vanilla-music/vanilla/tree/master/app/src/main/java/ch/blinkenlights/bastp). There is a standalone repo for it: https://github.com/adrian-bl/bastp Now, when a track is played, you call the `setReplayGainValue` function which, in turn, calls BASTP's `getTags()`, which eventually proceeds to the only part of code that is of interest for us, https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/LameHeader.java#L139 There, it computes the replay gain.

This is the part we are missing in our current library, everything else could be done using our current solution I think (reading replay gain tags, creating new tags).

Could you try to replace the call to `setReplayGainValue` to a method of your own that computes the replay gain and creates the tags accordingly if they are not already present, using jaudiotagger? After that, you would only need to modify the `tags.containsKey` lines with a call to jaudiotagger's equivalent.

Overall, this would prevent using two tagging libraries and improve the performance of your solution. Could you do that?

Thanks again, and if you have any questions I can help!

**Comment by knacky34** [comment]
I've replace BASTP with jaudiotagger and it's true that it's much better than have two tagging libraries

**Comment by AdrienPoupa** [comment]
Many thanks, that's much better!

One remark though: now, from what I see, you're extracting the replaygain from existing tags and applying it to the songs that already contain the info. However, for a song that does not have it, you do not compute it so it would not be applied, unless I missed something.

I think it is missing [this part](https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/LameHeader.java#L139) where it was extracting the replaygain directly from the file and not the tags.

**Comment by knacky34** [comment]
Yes I will add supports to read Lame Header tomorrow.

when i call `AudioFile.getTag()` if the file is a FLAC or OGG that is using VorbisComments, is this function gets VorbisComment tags too?

**Comment by knacky34** [comment]
Ok I will try it later, Good night !

**Comment by knacky34** [comment]
Yeah ! I think it will works in all case now !

**Comment by knacky34** [comment]
what file format is used ?

**Comment by AdrienPoupa** [comment]
MP3.

Interestingly, if I enable the replay track but leave everything to 0, it seems to work.

Also, the error seems to occur only on the first attempt to play the track (maybe an issue with computing the replay gain?)

**Comment by knacky34** [comment]
On my device working, I've no problems ...
Is your song have replaygain meta if yes which software do you use to create RG metadatas

**Comment by AdrienPoupa** [comment]
I have no idea if it has the meta, I never used this feature before. i will try to investigate and get back to you asap.

**Comment by AdrienPoupa** [comment]
Example of a file that was causing issue on the first load:

```
Tag content:
	TALB:Text="Broken Dream Remixes"; 
	TPE1:Text="Da Fresh"; 
	COMM:Language="English"; Text="Enjoy..."; 
	TSSE:Text="Lame 3.90.3 / Alt-Preset Standard"; 
	TCON:Text="Electronic"; 
	TLAN:Text="Eng"; 
	TPUB:Text="Hypnotic"; 
	TIT2:Text="Broken Dream  Original"; 
	TRCK:Text="2"; 
	TYERTDAT:org.jaudiotagger.tag.id3.TyerTdatAggregatedFrame@b1a8849
	TXXX:Description="Rip date"; Text="2006-05-11"; 
	TXXX:Description="Source"; Text="Vinyl"; 
	TXXX:Description="Ripping tool"; Text="Eac"; 
	TXXX:Description="Release type"; Text="Normal Release"; 
	TXXX:Description="Catalog #"; Text="Hypno036-1"; 
	PRIV:Owner="http://www.cdtag.com"; Data="6 bytes"; 
```

**Comment by knacky34** [comment]
Is the problem happen with any files or just a few ?

**Comment by AdrienPoupa** [comment]
If I try to play the file, I got an error. If I retry, it works until the next reboot of the application. I can send you the file by email if you give me your address.

Just some files, but always the same apparently

**Comment by knacky34** [comment]
yes please gw.janssoone@gmail.com

**Comment by AdrienPoupa** [comment]
No more bugs for me - congrats!

**Pull request merged**
