### PR TITLE
Auto queue stuck

### PR DESCRIPTION
**Pull request by soncaokim**
While processing the play requests (ie for Auto), dont use the services provided by MusicPlayerRemote proxy to access MusicService.

This proxy does not handling the latter's init/lifecycle, hence may nullify any attempt to use the latter.

This PR probably fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/237

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
The app got rejected again, maybe this fixes it?

Voice commands
Your app does not support all of the required voice commands. You can read more about how to support Voice Actions in the Android Developers Help Center.
For example, your app does not switch audio tracks when recognizing and responding to a voice command intent. When being asked to play “X,” the app remains on “Y.” The app should switch over and play “X.”

**Comment by soncaokim** [comment]
Hmm, there is indeed a small chance that this will make it pass. The most relevant thing that I see is that the queue was stuck and hence doesnt allow switching to new song. 

I'm finishing few touches on this branch and will remove the draft state of this PR.

However:
- We dont explicitly support search as specified by https://developer.android.com/training/cars/media#display_search
  Do you know how one can trigger these voice commands?
- The queue being stuck bug has been around since 1 year (see the bug in the PR description), how come Google is acting stricter this time? Is that related to the recent target API change, from v28 to v29?

**Comment by AdrienPoupa** [comment]
>  Do you know how one can trigger these voice commands?

I would assume by hitting the mic icon as shown in your link?

> The queue being stuck bug has been around since 1 year (see the bug in the PR description), how come Google is acting stricter this time? Is that related to the recent target API change, from v28 to v29?

Not sure but they must have tightened the requirements for an Auto app. I guess if this does not make it pass I'll just disable Auto temporarily to publish the update.

**Comment by soncaokim** [comment]
@AdrienPoupa I let you review and do some testing on your end

**Comment by soncaokim** [comment]
That mic icon indeed reacts to something, it is not photoshopped in 😀

I ve managed to skip songs with that, but "play X"/"play X on Vinyl" command  would just invite me to install Youtube Music.

**Comment by soncaokim** [comment]
> managed to skip songs with that, but "play X"/"play X on Vinyl" command would just invite me to install Youtube Music

which is normal to me given that we dont support onSearch callback

**Comment by secure-username** [comment]
> 
> 
> > managed to skip songs with that, but "play X"/"play X on Vinyl" command would just invite me to install Youtube Music
> 
> which is normal to me given that we dont support onSearch callback

Is there a reason we don't support onSearch? It would be a very useful feature for Auto.

**Pull request merged**
