### PR TITLE
More info in the song's Details dialog

### PR DESCRIPTION
**Pull request by soncaokim**

### CODE REVIEW

**Comment by Octoton** [comment]
Don't know how much of a work in progress this is but cannot unsee that you are creating new string definition for thing that are already there and for some language translated. In order the new label that you are creating seems to all exist with the names:
sort_order_date_added
sort_order_date_modified
disc_number ?
title
track_number
artists
album
album_artist
genre
year

**Comment by soncaokim** [comment]
For the `sort*` strings: yeah this is intentionnal, since I'm not 100% sure that the strings are all the same in all translations.

For the others: I might have overlooked, will review.

**Comment by soncaokim** [comment]
> For the `sort*` strings: yeah this is intentionnal, since I'm not 100% sure that the strings are all the same in all translations.
> 
> For the others: I might have overlooked, will review.

Should be better with the last commit

**Comment by soncaokim** [comment]
@AdrienPoupa Can this PR be merged please?

**Comment by soncaokim** [comment]
merged

**Pull request merged**
