### PR TITLE
Discog v3

### PR DESCRIPTION
**Pull request by soncaokim**
Work in progress.

This brings support to multi-artist albums and fixes https://github.com/AdrienPoupa/VinylMusicPlayer/issues/323

- [x] Extract album artist from ID3 tags and use that for album grouping/sorting
- [x] unknown artist is shown as empty on artist tab
- [x] given a song with album artist A and artist "A & B", only "A & B" is shown on artist tab. 
- [x] show album artist on top of album detail page if there is one, else fallback to first song's artist
- [ ] Handle compilation albums (with TCMP/cpil tag)

### CODE REVIEW

**Comment by soncaokim** [comment]
Please have a look.

I'm caressing the idea to isolate the support for compilation album in another pull request, to keep this one functionally minimal.

**Comment by AdrienPoupa** [comment]
Looks good to me

**Comment by soncaokim** [comment]
> Looks good to me

Does it imply the same for the branch 'multi-disc-track-sorting' since this one contains changes from that one? :-P

**Comment by Octoton** [comment]
Seems to work really well for multi-artist album

**Comment by soncaokim** [comment]
@AdrienPoupa Can this be shipped or you have a reason to hold it back?

**Comment by AdrienPoupa** [comment]
No reason, just busy I guess :p

**Comment by soncaokim** [comment]
> No reason, just busy I guess :p

Thanks for finding the time 👍

**Comment by AdrienPoupa** [comment]
You're welcome, thanks for the contribution. I'll draft a new release soon.

**Pull request merged**
