### PR TITLE
Fixed or added German translations

### PR DESCRIPTION
**Pull request by tschlegeldigos**
Hi all,

I revised the German translation (native speaker here) and used the basic res/values/strings.xml as basis.

The only thing I was unsure about is "Limited listing while driving", which I translated to "Auflisten beim Fahren begrenzen". What is the context here, does this refer to performance issues while listing the titles?

### CODE REVIEW

**Comment by AdrienPoupa** [comment]
Thanks!

> The only thing I was unsure about is "Limited listing while driving", which I translated to "Auflisten beim Fahren begrenzen". What is the context here, does this refer to performance issues while listing the titles?

This is for Android Auto, that shows an interface with limited information to reduce driver's distraction.

**Comment by AdrienPoupa** [comment]
The pipeline passed, please let me know if you want to update the Auto translation or merge as is.

**Comment by tschlegeldigos** [comment]
> 
> 
> The pipeline passed, please let me know if you want to update the Auto translation or merge as is.

I'd like to revise it, since the translation I provided does not fit in this context. One moment please.

**Comment by tschlegeldigos** [comment]
The immediate translations of "Listing" are not clear in German, so I decided to translate it to something like "reduce list view while driving". If this is fine, you can merge it.

**Pull request merged**
