### PR TITLE
Queue restore crash

### PR DESCRIPTION
**Pull request by soncaokim**
This is an attempt to fix the following crash.
The approach chosen is to ignore the saved queue - i.e. degraded service.
```
java.lang.ArrayIndexOutOfBoundsException: length=1620; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.restoreUniqueId(Unknown Source:40)
at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.<init>(Unknown Source:63)
at com.poupa.vinylmusicplayer.service.MusicService.restoreQueuesAndPositionIfNecessary(Unknown Source:99)
at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:28)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:250)
at android.os.HandlerThrbead.run(HandlerThread.java:67)
```

Not reproducible, probably linked to a forced-stop after multiple queue manipulation actions.

### CODE REVIEW

**Comment by soncaokim** [comment]
@Octoton Please have a look at this and tell me if you have any better idea to handle this?
Thanks

**Comment by Octoton** [comment]
Seems to be caused by restoreUniqueId when the restore queue is for unkown reason corrupted, the line:
```
originalQueue.get(queue.get(i).index).setUniqueId(uniqueId); 
```
when queue.get(i).index is INVALID_POSITION (or just out of bound), I made the mistake of thinking that in the queue index will always be a correct value...
we could stop the crash by just checking if index is out of bound before calling get(...index), but if the index is corrupt the queue cannot really be trust in the futur and I am not sure what is best:
 - In restoreUniqueID, if a index out of bound is found the queue need to be revert(), and all index/uniqueId recreated in the order of the originalQueue
 - or as you have done we trash the all queue

However, it is strange to me that the index could be INVALID_POSITION on restore, I will have to check this a bit more later this week

**Comment by soncaokim** [comment]
As stated, I had this once, probably after multiple add/remve and a forced stop. Unless you see a straight forward fix, we could stick with this.

I will probably need to restore the previous shuffle mode (according to the choice in the prefs) though.

**Comment by Octoton** [comment]
True enough, for the shuffle mode you don't need to check the preference as it is already done before, just save the queue shuffle mode before instantiation a new one:
old mode = playingQueue .getShuffleMode()
playingQueue = new Queue
playingQueue.setShuffle(old mode)

**Comment by soncaokim** [comment]
If there is no blocking comment, I'll merge this PR this weekend

**Comment by Octoton** [comment]
Seems good to me

**Pull request merged**
