### PR TITLE
Lint

### PR DESCRIPTION
**Pull request by soncaokim**

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@soncaokim IDK about the AppCompat and Core library upgrades... https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_150_2. AppCompat 1.3.0 uses Core 1.5.0 internally too. IDK if anything will break because of this, so be careful at least.

**Comment by TacoTheDank** [comment]
Also, material-dialogs 0.9.6.0 is already hosted on mavenCentral (see the app [Slide](https://github.com/ccrama/Slide/blob/master/app/build.gradle#L114) that I help maintain, notice there's no jcenter in the root build.gradle). Material-CAB, will have to be migrated, though, as the older versions don't exist on mavenCentral.

**Comment by soncaokim** [comment]
> @soncaokim IDK about the AppCompat and Core library upgrades... https://developer.android.com/jetpack/androidx/releases/core#core_and_core-ktx_version_150_2. AppCompat 1.3.0 uses Core 1.5.0 internally too. IDK if anything will break because of this, so be careful at least.

Hi,

Can you please be more specific on what is the danger?
I'm testing with a continous build where all branches are integrated, including this one, and dont see any apparent issue. 

What is the behaviour should I pay attention to?

**Comment by TacoTheDank** [comment]
@soncaokim Specifically, the note that says "Note: This version will only compile against the Android 11 SDK." Idk if that was maybe incorrect on the library devs' part.

**Comment by soncaokim** [comment]
> @soncaokim Specifically, the note that says "Note: This version will only compile against the Android 11 SDK." Idk if that was maybe incorrect on the library devs' part.

This is written in a big banner on the top of the page - guess that I need to be retrained on how to read the doc :-)

Even if I'm running with this PR on my Android 10 device, I will rollback the change to err on the safe side.

Thanks @TacoTheDank for the review

**Pull request merged**
