### PR TITLE
add circleci

### PR DESCRIPTION
**Pull request by soncaokim**
This is a proposal to add continuous integration to the project, via the circleci.com. 

The benefit is to help contributors/maintainers to offload the merge/build/(ultimately tests as well) to a dedicated service, and get back the status via github interface.

Quick walk through different added files:

- .circleci/config.yml: Required for circleci to pickup and automate the build. Mostly based from their sample, beside the "Merge Feature Branches" step (more on that later).
- .circleci/circleci-unsecured.jks: release signing key (Android wont allow APK upgrade otherwise).
- .circleci/merge-feature-branches: script called by circleci (see config.yml) at the beginning of the build steps, to merge all the open branches and build an APK having all the features. This is not a mandatory step but it comes handy for play with multiples PR at the same time.
- .circleci/sync-tracking-branches: Independent script, does what the name says.

My proposal is to:
- merge this into vinyl, probably without the merge-feature-branches step.
- configure (it's on you @AdrienPoupa) circleci.com integration on their site.
- optionally, insert the CI badge on README.md

### CODE REVIEW

**Comment by soncaokim** [comment]
that was quick! :-)

@AdrienPoupa do you plan to add the build badge to the readme.md? (cf. https://circleci.com/docs/2.0/status-badges/)

**Comment by soncaokim** [comment]
@arkon @kabouzeid, it doesnt turn out to be very hard to have CI enabled. 

Do you want to have the same implemented on Phonograph side?

**Comment by kabouzeid** [comment]
What does CI do if you don’t have any tests?

**Comment by arkon** [comment]
Yeah, I do like having CI for producing APKs and doing dry run builds for PRs.

I don't have the power to set it up for the Phonograph repo though.

**Comment by kabouzeid** [comment]
Sounds reasonable. Starting April 10th, I'll have time for Phonograph again. If this is not too much work, I could setup CI even before that.

**Comment by soncaokim** [comment]
> What does CI do if you don’t have any tests?

Automatising build at least (as Eugene stated). It helps avoiding non mergeable PR, non buildable ones, and rants from contributors like I ve made last time.

It opens door for automatic tests as well.

> If this is not too much work...

For Vinyl I believe that was some what easy (based on the delay between the time Adrien merged and the time the first build popped up).

For Phonograph there might be one extra step to do: dissociate the release signing key (refer to your personal drive Karim) and the ci signing key (that I provided).

Son

**Comment by GeoZac** [comment]
Seems the CI implementaion is buggy, One of the primary reason stated for CI was to avoid non-mergeable PRs
Ref: [PullRequest](https://github.com/AdrienPoupa/VinylMusicPlayer/pull/125)

**Comment by soncaokim** [comment]
@GeoZac

Can you give more pricision on what doesnt work as expected?

I dont see the connection between the comment and the provided ref neither.

S

**Comment by soncaokim** [comment]
@GeoZac, if I do guess correctly, you expect to see build status (the green check mark) to appear on PR as well? 

Those checkmarks are not present on the three most recent PRs (while they do appear on master commit and on the test PR).

I suppose that's Adrien's intention to configure it like that, not to build PR from forks.
It's possible to configure it:
image

**Pull request merged**
