### PR TITLE
Fixed some German translations

### PR DESCRIPTION
**Pull request by tschlegeldigos**
While playing around with different font sizes etc., I noticed some leftover minor language errors and one or two excessively long lines, so I revised it again.

The reason for this PR to be WIP is, that the usage of periods is rather inconsistent in the settings (which also applies to the original English texts, so it seems to have carried over).

If desired, I could unify it (I tend towards always setting a period, if it is a sentence or at least an ellipsis), but I don't want to unnecessarily break consistencies across languages, so I would leave the decision on your side.

### CODE REVIEW

**Comment by soncaokim** [comment]
Not sure that I fully understand your comment, but as a general rule I would put
- ellipsis ending all menu item texts that will require further input from user.
- no ellipsis (nor point) for all actions that will be applied immediately.

I dont have any clue if this kind of rule is applicable to all languages (especially non latin based like jp, cn, ko,...). So we'd better leave that to the native speakers.

**Comment by tschlegeldigos** [comment]
Ah, this got mixed up in translation! :)

I meant 'ellipsis' as in 'incomplete / very short sentences', in contrast to those spanning several lines.

Basically I noted, that some of them (e.g. `Use the classic notification design.`) end in a period, while e.g. `Animate playing song icon` doesn't, despite both being similar in structure and both being settings descriptions.

I was just wondering, if it made any sense to make all (or none) of them end in periods, although when considering special cases such as strings containing several sentences (e.g. `Currently only synchronized lyrics in LRC format are supported. Either embedded or as a separate file.`), I would tend to the former.

We could also just leave it, as it is, but this would just be a small suggestion.

**Comment by soncaokim** [comment]
> I was just wondering, if it made any sense to make all (or none) of them end in periods, although when considering special cases such as strings containing several sentences (e.g. `Currently only synchronized lyrics in LRC format are supported. Either embedded or as a separate file.`), I would tend to the former.

Yes for me.

**Comment by soncaokim** [comment]
To be clear, I would remove ending period, except multiple phrases situations

**Comment by tschlegeldigos** [comment]
> To be clear, I would remove ending period, except multiple phrases situations

Thanks for the clarification, I would have interpreted it the other way around.

I did this now only for the de/strings.xml, to not create confusion by extending this PR too much. I'll open another one with clear association.

**Pull request merged**
