### PR TITLE
Animated playing indicator icon

### PR DESCRIPTION
**Pull request by soncaokim**
This PR replaces the playing song indicator icon (currently a broadcasting loud speaker) by a rotating vinyl disc.

### CODE REVIEW

**Comment by soncaokim** [comment]
For the playing queue, the rotating vinyl is still not animated the very first launch.

If a song in the queue is tapped, or the queue is updated, then the animation is played. 

I'm retagging this PR as WIP for the moment.

**Comment by AdrienPoupa** [comment]
Hey, are you sure this doesn't affect the performances? Personally I would be fine with just the song title in bold without an icon

**Comment by soncaokim** [comment]
Comparing to other tasks (music decoding and streaming) this is negligible. I dont see any noticeable hit with my day to day usage.

**Comment by paolovalerdi** [comment]
I think it would be much better to just use an AnimtedVectorDrawable for this

**Comment by soncaokim** [comment]
Noted, I ll look this up. What would be the benefits?

**Comment by paolovalerdi** [comment]
You would only call .start() on it and afaik it better in performance for this kind of animations

**Comment by soncaokim** [comment]
I've been experimenting with the animated-vector drawables. While it would offload the animation to the dedicated thread, I'm not sure that's something worth doing - given the tiny size of the icon to be animated.

Moreover, providing an _acceptable_ vector image appears to be more work than I anticipated, let alone the animation bits :-)

**Comment by soncaokim** [comment]
@AdrienPoupa please review this

**Comment by AdrienPoupa** [comment]
I'll have a look this weekend, thanks!

**Comment by soncaokim** [comment]
@AdrienPoupa what is the final verdict please?

**Comment by soncaokim** [comment]
If the animation is a concern for negative CPU impact, it can be disabled by default (via a new config setting)

**Comment by AdrienPoupa** [comment]
This was long overdue, thanks a lot!

**Pull request merged**
