### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by auanasgheps**
Remove duplicated line

Maybe you could use a translation platform such as https://crowdin.com/, it's free and would ease translation updates and avoid errors like this one.

### CODE REVIEW

**Comment by soncaokim** [comment]
The build is still failing: https://app.circleci.com/pipelines/github/AdrienPoupa/VinylMusicPlayer/624/workflows/6b5eed86-f703-42ac-9b6a-3de33cf30d71/jobs/709?invite=true#step-106-19

@auanasgheps Can you please confirm this is building OK on your end ?

**Comment by soncaokim** [comment]
@AdrienPoupa To help contributors that dont have a build environment, is that possible to enable pull request continuous integration builds on circleci? There is an option on their UI - "Build forked pull requests" - that seems to match.

The circleci build result will be given back to github.

**Comment by AdrienPoupa** [comment]
Done, good idea :)

**Comment by soncaokim** [comment]
@auanasgheps I've tried a fix here : https://github.com/AdrienPoupa/VinylMusicPlayer/pull/478
I'm holding it in draft mode - can you please have a look?

**Comment by auanasgheps** [comment]
Yes, your proposal looks good. I've commented there. 
I'm sorry for the trouble.

**Pull request merged**
