### PR TITLE
Update Korean translation

### PR DESCRIPTION
**Pull request by yurical**
Hello. Thanks for developing great music player.
This PR contains general updates and fixes for Korean translation.

### CODE REVIEW

**Comment by yurical** [comment]
... and it seems that the circleci failure is not related to this PR.

**Comment by soncaokim** [comment]
> ... and it seems that the circleci failure is not related to this PR.

Restarted the CI job

**Comment by yurical** [comment]
It's good to go now.

**Comment by AdrienPoupa** [comment]
Thanks!

**Pull request merged**
